version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data/mongodb/data:/data/db
      - ./scripts/mongo:/docker-entrypoint-initdb.d
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - formsite

  frontend:
    image: node
    container_name: frontend
    working_dir: /home/node/frontend/
    ports:
      - "$APP_PORT:$APP_PORT"
    environment:
      - PORT=$APP_PORT
      - REACT_APP_API_BASE_URL=$API_BASE_URL
      - REACT_APP_API_PORT=$API_PORT
    volumes:
      - ../frontend:/home/node/frontend
      - ./yarn/frontend:/home/node/frontend/.yarn
      - ./node/frontend/node_modules:/home/node/frontend/node_modules
    command: yarn run start
    networks:
      - formsite

  backend:
    image: node
    container_name: backend
    working_dir: /home/node/backend/
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - REGISTRATION_ENABLED=${REGISTRATION_ENABLED}
      - LOGIN_ENABLED=${LOGIN_ENABLED}
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ../backend:/home/node/backend
      - ./yarn/backend:/home/node/backend/.yarn
      - ./node/backend/node_modules:/home/node/backend/node_modules
    command: yarn run watch
    networks:
      - formsite

networks:
  formsite:
    external: true
