version: "3.7"

services:
  nginx:
    image: kevinedwards/formsite-web:0.0.3
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - prod

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backend:
    image: kevinedwards/formsite-api:0.0.2
    container_name: backend
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      PORT: 3003
      REGISTRATION_ENABLED: 0
      LOGIN_ENABLED: 1
      DB_URI: mongodb://mongoadmin:secret@mongodb:27017/dynalife?authSource=admin
      JWT_SECRET: lshfosnfoshdfohvpng;w4vj0wu0ajc0iayvashvacaf
    networks:
      - prod

networks:
  prod:
    external: true
