version: "3"

services:
  frontend-init:
    image: node
    volumes:
      - ../frontend:/home/node/frontend
      - ./data/yarn/frontend:/home/node/frontend/.yarn
      - ./data/node/frontend/node_modules:/home/node/frontend/node_modules
      - ./src/scripts/frontend-init.sh:/home/node/frontend/frontend-init.sh
    working_dir: /home/node/frontend/
    command: bash /home/node/frontend/frontend-init.sh

  frontend_base: &frontend_base
    image: node
    volumes:
      - ../frontend:/home/node/frontend
      - ./data/yarn/frontend:/home/node/frontend/.yarn
      - ./data/node/frontend/node_modules:/home/node/frontend/node_modules
    working_dir: /home/node/frontend/

  frontend:
    <<: *frontend_base
    command: ${CMD}

  backend-init:
    image: node
    volumes:
      - ../backend:/home/node/backend
      - ./data/yarn/backend:/home/node/backend/.yarn
      - ./data/node/backend/node_modules:/home/node/backend/node_modules
      - ./src/scripts/backend-init.sh:/home/node/backend/backend-init.sh
    working_dir: /home/node/backend/
    command: bash /home/node/backend/backend-init.sh

  backend-base: &backend-base
    image: node
    environment:
      - DB_URI=$DB_URI
    volumes:
      - ../backend:/home/node/backend
      - ./data/yarn/backend:/home/node/backend/.yarn
      - ./data/node/backend/node_modules:/home/node/backend/node_modules
    working_dir: /home/node/backend/
    networks:
      - formsite

  backend:
    <<: *backend-base
    command: ${CMD}

networks:
  formsite:
    external: true