version: "3.7"

services:
  frontend:
    image: node
    container_name: frontend
    working_dir: /home/node/frontend/
    ports:
      - "3002:3002"
    env_file:
      - ./env/.env-frontend
    volumes:
      - ../../frontend:/home/node/frontend
      - ./node/frontend/node_modules:/home/node/frontend/node_modules
    command: npm run start
    networks:
      - dev

  backend:
    image: kevinedwards/formsite-api:0.0.1
    container_name: backend
    ports:
      - "3003:3003"
    env_file:
      - ./env/.env-backend
    networks:
      - dev

networks:
  dev:
    external: true

docker run -itd \
  -p 8000:8000 \
  -p 9000:9000 \
  --name=portainer \
  --network prod \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(pwd)/portainer/data:/data \
  portainer/portainer-ce

docker run -itd \
  -p 8081:8081 \
  --name=mongoex \
  --network prod \
  --restart=always \
  -e ME_CONFIG_OPTIONS_EDITORTHEME=ambiance \
  -e ME_CONFIG_MONGODB_SERVER=mongodb \
  -e ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin \
  -e ME_CONFIG_MONGODB_ADMINPASSWORD=secret \
  mongo-express

docker run -itd \
  -e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
  -e MONGO_INITDB_ROOT_PASSWORD=secret \
  -v $(pwd)/mongodb/datadir:/data/db \
  --network prod \
  --name mongodb \
  mongo

docker run -it \
  --network prod \
  -v $(pwd):/mongostuff \
  --rm mongo \
  mongoimport --host mongodb \
  -u mongoadmin \
  -p secret \
  -d dynalife \
  -c forms \
  --file /mongostuff/forms.json \
  --jsonArray \
  --authenticationDatabase admin

docker run -itd \
  --network prod \
  --name backend \
  -p 3001:3001 \
  -e NODE_ENV=production \
  -e PORT=3001 \
  -e REGISTRATION_ENABLED=0 \
  -e LOGIN_ENABLED=1 \
  -e DB_URI='mongodb://mongoadmin:secret@mongodb:27017/dynalife?authSource=admin' \
  -e JWT_SECRET='lshfosnfoshdfohvpng;w4vj0wu0ajc0iayvashvacaf' \
  kevinedwards/formsite-api:0.0.2


docker run -itd \
  --network prod \
  --name frontend \
  -p 80:80 \
  -e NODE_ENV=production \
  kevinedwards/formsite-web:0.0.1
