version: "3"

services:
  frontend-init:
    image: node
    volumes:
      - ../../frontend:/home/node/frontend
    working_dir: /home/node/frontend
    command: npx create-react-app .

  frontend_base: &frontend_base
    image: node
    volumes:
      - ../../frontend:/home/node/frontend
      - ./node/frontend/node_modules:/home/node/frontend/node_modules
    working_dir: /home/node/frontend/

  frontend:
    <<: *frontend_base
    command: ${CMD} ${PKG}

  backend-init:
    image: node
    volumes:
      - ../../backend:/home/node/backend
    working_dir: /home/node/backend
    command: npm init -y

  backend_base: &backend_base
    image: node
    volumes:
      - ../../backend:/home/node/backend
      - ./node/backend/node_modules:/home/node/backend/node_modules
    working_dir: /home/node/backend/

  backend:
    <<: *backend_base
    env_file:
      - ./env/.env-backend
    command: ${CMD} ${PKG}
