version: "3.7"

services:
  frontend:
    image: node
    container_name: frontend
    working_dir: /home/node/frontend/
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    environment:
      - PORT=${REACT_APP_PORT}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_API_PORT=${REACT_APP_API_PORT}
    volumes:
      - ../../frontend:/home/node/frontend
      - ./node/frontend/node_modules:/home/node/frontend/node_modules
    command: npm run start
    networks:
      - formsite

  backend:
    image: node
    container_name: backend
    working_dir: /home/node/backend/
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${NODE_PORT}
      - REGISTRATION_ENABLED=${REGISTRATION_ENABLED}
      - LOGIN_ENABLED=${LOGIN_ENABLED}
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ../../backend:/home/node/backend
      - ./node/backend/node_modules:/home/node/backend/node_modules
    command: npm run watch
    networks:
      - formsite
      - admin

networks:
  formsite:
    external: true
  admin:
    external: true
